import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Josefin_Sans } from "next/font/google"

const inter = Inter({ subsets: ["latin"] });

const josefin = Josefin_Sans({
  subsets: ['latin'],
  variable: "--font-josefin",
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={josefin.variable}>
      <body className="bg-soft-red-gradiant h-screen">{children}</body>
    </html >
  );
}
